In [1]:
import numpy as np

In [16]:
a = np.array([[1, 0, 0], [0, 1, 0]])
b = np.array([[4, 1], [2, 2]])

print(a)
print(b)
print(np.hstack((a, b)))

[[1 0 0]
 [0 1 0]]
[[4 1]
 [2 2]]
[[1 0 0 4 1]
 [0 1 0 2 2]]


In [61]:
M = np.random.randint(0, 7, size = (4,4))
M

array([[5, 6, 1, 1],
       [6, 0, 5, 2],
       [0, 1, 3, 4],
       [0, 6, 4, 6]])

In [62]:
a = np.random.randint(0, 4, size = (5, ))
b = np.random.randint(0, 4, size = (5, ))

print(a)
print(b)
print(M[a, b])

[1 2 2 0 1]
[2 1 3 2 1]
[5 1 4 1 0]


In [63]:
np.trace(M)

14

In [66]:
print(np.diag(M))
print(np.count_nonzero(np.diag(M)))

[5 0 3 6]
3


In [75]:
a = np.random.randint(-5, 5, size = (4, 4))
b = np.random.randint(-5, 5, size = (4, 4))

In [76]:
print(a)
print(b)

b = np.where(a<0, 0, b)

print(b)

[[ 2 -2 -3 -2]
 [ 2  2  3 -3]
 [ 1  3 -5 -1]
 [-2  1 -3 -4]]
[[ 4  1  0  3]
 [-5  4 -3 -5]
 [-5  4 -3 -2]
 [ 3  3 -4 -5]]
[[ 4  0  0  0]
 [-5  4 -3  0]
 [-5  4  0  0]
 [ 0  3  0  0]]


In [80]:
print(a)
print(np.mean(a, axis = 0))

[[ 2 -2 -3 -2]
 [ 2  2  3 -3]
 [ 1  3 -5 -1]
 [-2  1 -3 -4]]
[ 0.75  1.   -2.   -2.5 ]


In [94]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [97]:
a = np.hstack((a - np.mean(a, axis = 0), np.zeros((4,1))))
print(a)

[[ 1.25 -3.   -1.    0.5   0.  ]
 [ 1.25  1.    5.   -0.5   0.  ]
 [ 0.25  2.   -3.    1.5   0.  ]
 [-2.75  0.   -1.   -1.5   0.  ]]


In [98]:
a = np.where(np.sum(a, axis = 0),a/np.sum(a*a, axis = 0), a)

<ipython-input-98-c8683cb73d01>:1: RuntimeWarning: invalid value encountered in true_divide
  a = np.where(np.sum(a, axis = 0),a/np.sum(a*a, axis = 0), a)
